name: 'Check categories'
description: 'Check the Helm Charts categories'
inputs:
  command:
    description: 'Parameters for the chart-testing tool'
    required: true
    default: 'check-categories'
  categories-file:
    description: 'File containing the list of allowed categories'
    required: false
    default: 'CHART_CATEGORIES'

outputs:
  categories-are-correct:
    description: 'Wheter or not the categories are correct'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.categories-file }}
